spring:
  profiles:
    active: dev
  application.name: consumer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: dev
        group: dev
        service: ${spring.application.name}
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080
      eager: true
server:
  port: 1001
