server:
  port: 2527

# 开启openfeign所在包的日志级别
logging:
  level:
    springboot.randomconsumer.feign: debug

spring:
  profiles:
    active: dev
  application:
    name: random-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.127.142:8848
        namespace: ac169f42-69b0-4dea-be4f-c43848d5d115
        service: ${spring.application.name}
        group: cloudTest
      config:
        server-addr: 192.168.127.142:8848
        namespace: ac169f42-69b0-4dea-be4f-c43848d5d115
        group: cloudTest
        import-check:
          enabled: true
    loadbalancer:
      nacos:
        enabled: false
    openfeign:
      client:
        config:
          default:
            connectTimeout: 2000
            read-timeout: 7000
            loggerLevel: BASIC

---
spring:
  config:
    import:
      - nacos:consumer.yaml
    activate:
      on-profile: dev

