dubbo:
  consumer:
    threads: 200       # 消费者端的最大线程数
    core-threads: 100  # 核心线程数
    queues: 500        # 线程池队列大小
  application:
    name: Dubbo_Business
    qos-port: 33333
  protocol:
    name: tri
    port: 50059
    # 线程池配置
    threads: 500       # 最大线程数
    core-threads: 200  # 核心线程数
    queues: 1000       # 线程池队列大小
  registry:
    address: nacos://127.0.0.1:8848
    parameters:
      namespace: 65ca8fdb-2d8c-4cb7-8d21-7916701198f3
      group: dubbo_demo
#      register-consumer-url: true # 启用消费者注册

spring:
  application:
    name: Dubbo_Business
  profiles:
    active: test
server:
  port: 3344

seata:
  enabled: true
  application-id: dubbo-samples-seata
  tx-service-group: default_tx_group
  service:
    vgroup-mapping:
      default_tx_group: default
    grouplist:
      default: ${seata.address:127.0.0.1}:${seata.port:8091}
  registry:
    type: file
  config:
    type: file